                                                                                                                                                                                                                                                                                                            -- =============================================
                                                                                                                                                                                                                                                                                                            -- PAYMENT PLAN HISTORY - Migration
                                                                                                                                                                                                                                                                                                            -- Historial de planes de pago generados
                                                                                                                                                                                                                                                                                                            -- =============================================

                                                                                                                                                                                                                                                                                                            -- Tabla principal
                                                                                                                                                                                                                                                                                                            CREATE TABLE public.payment_plan_history (
                                                                                                                                                                                                                                                                                                              id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
                                                                                                                                                                                                                                                                                                              user_id UUID REFERENCES auth.users(id) NOT NULL,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Datos del cliente
                                                                                                                                                                                                                                                                                                              client_name TEXT NOT NULL,
                                                                                                                                                                                                                                                                                                              client_phone TEXT,
                                                                                                                                                                                                                                                                                                              client_email TEXT,
                                                                                                                                                                                                                                                                                                              unit_type TEXT,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Valores financieros (guardados en moneda original)
                                                                                                                                                                                                                                                                                                              property_value DECIMAL NOT NULL,
                                                                                                                                                                                                                                                                                                              discounted_value DECIMAL NOT NULL,
                                                                                                                                                                                                                                                                                                              reservation DECIMAL,
                                                                                                                                                                                                                                                                                                              initial_percentage DECIMAL,
                                                                                                                                                                                                                                                                                                              construction_percentage DECIMAL,
                                                                                                                                                                                                                                                                                                              delivery_percentage DECIMAL,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Resultados calculados
                                                                                                                                                                                                                                                                                                              total_initial DECIMAL,
                                                                                                                                                                                                                                                                                                              on_contract_signing DECIMAL,
                                                                                                                                                                                                                                                                                                              during_construction DECIMAL,
                                                                                                                                                                                                                                                                                                              installments_count INTEGER,
                                                                                                                                                                                                                                                                                                              installment_amount DECIMAL,
                                                                                                                                                                                                                                                                                                              delivery_amount DECIMAL,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Pagos extraordinarios (JSON array)
                                                                                                                                                                                                                                                                                                              extra_payments JSONB,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Metadata
                                                                                                                                                                                                                                                                                                              currency TEXT DEFAULT 'USD',
                                                                                                                                                                                                                                                                                                              sell_rate DECIMAL,
                                                                                                                                                                                                                                                                                                              payment_frequency TEXT,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Fechas del plan
                                                                                                                                                                                                                                                                                                              start_month INTEGER,
                                                                                                                                                                                                                                                                                                              start_year INTEGER,
                                                                                                                                                                                                                                                                                                              end_month INTEGER,
                                                                                                                                                                                                                                                                                                              end_year INTEGER,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Promoción
                                                                                                                                                                                                                                                                                                              promotion_enabled BOOLEAN DEFAULT FALSE,
                                                                                                                                                                                                                                                                                                              promotion_name TEXT,
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              -- Tipo de generación
                                                                                                                                                                                                                                                                                                              generated_type TEXT, -- 'pdf' o 'image'
                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                              created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
                                                                                                                                                                                                                                                                                                            );

                                                                                                                                                                                                                                                                                                            -- Índices para búsqueda eficiente
                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_payment_history_user ON public.payment_plan_history(user_id);
                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_payment_history_client ON public.payment_plan_history(client_name);
                                                                                                                                                                                                                                                                                                            CREATE INDEX idx_payment_history_date ON public.payment_plan_history(created_at DESC);

                                                                                                                                                                                                                                                                                                            -- Habilitar Row Level Security
                                                                                                                                                                                                                                                                                                            ALTER TABLE public.payment_plan_history ENABLE ROW LEVEL SECURITY;

                                                                                                                                                                                                                                                                                                            -- Política: Usuarios pueden ver solo su propio historial
                                                                                                                                                                                                                                                                                                            CREATE POLICY "Users can view own payment history" ON public.payment_plan_history
                                                                                                                                                                                                                                                                                                              FOR SELECT USING (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                            -- Política: Usuarios pueden insertar en su propio historial
                                                                                                                                                                                                                                                                                                            CREATE POLICY "Users can insert own payment history" ON public.payment_plan_history
                                                                                                                                                                                                                                                                                                              FOR INSERT WITH CHECK (auth.uid() = user_id);

                                                                                                                                                                                                                                                                                                            -- Política: Supervisores pueden ver historial de todos
                                                                                                                                                                                                                                                                                                            CREATE POLICY "Supervisors can view all payment history" ON public.payment_plan_history
                                                                                                                                                                                                                                                                                                              FOR SELECT USING (
                                                                                                                                                                                                                                                                                                                EXISTS (
                                                                                                                                                                                                                                                                                                                  SELECT 1 FROM user_profiles 
                                                                                                                                                                                                                                                                                                                  WHERE user_profiles.id = auth.uid() 
                                                                                                                                                                                                                                                                                                                  AND user_profiles.role IN ('supervisor', 'admin')
                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                              );
